package trade

// FuturesUnitNames describes each FuturesUnit code. The table is Webull's;
// it is reproduced here because the API transmits only the number.
var FuturesUnitNames = map[FuturesUnit]string{
	1:  "Index points",
	2:  "Hong Kong dollars",
	3:  "US dollars",
	4:  "Bushels",
	5:  "Bushels 2",
	6:  "Futures contract",
	7:  "Short tons, 2000 pounds",
	8:  "Pounds",
	9:  "Gallons",
	10: "Metric tons, 2204.6 pounds",
	11: "Brazilian real",
	12: "Troy ounces",
	13: "British pounds",
	14: "Euros",
	15: "Mexican peso",
	16: "Czech koruna",
	17: "Polish zloty",
	18: "Israeli shekel",
	19: "Barrels",
	20: "Metric ton",
	21: "Australian dollar",
	22: "New Zealand dollar",
	23: "Canadian dollar",
	24: "Swiss franc",
	25: "Japanese yen",
	26: "South African rand",
	27: "Hungarian forint",
	28: "Korean won",
	29: "Million British thermal units",
	30: "Chinese renminbi",
	31: "Megawatt hours",
	41: "Megawatt",
	42: "Therms",
	51: "Environmental offset",
	52: "Basis points",
	53: "Metric tons (thousands)",
	54: "Gross tons",
	55: "Tons (thousands)",
	56: "Ton",
	57: "Bitcoin",
	58: "Russian ruble",
	59: "Indian rupee",
	60: "1 day of time charter",
	61: "Cubic meter",
	62: "Kiloliters",
	63: "Kilos",
	64: "Chilean peso",
	65: "Regional Greenhouse Gas Initiative allowances (RGGI)",
	66: "Hundredweight, 100 pounds",
	67: "Norwegian krone",
	68: "Allowance (emission)",
	69: "Board feet",
	70: "Grams",
	71: "Swedish krona",
	72: "Environmental credit",
	73: "Dry metric tons",
	74: "Shares",
	75: "Metric ton",
	76: "Malaysian ringgit",
	77: "Ether",
	78: "Pounds net weight",
	79: "Renewable Identification Number (RIN)",
	80: "Barrels (thousands)",
	81: "Troy ounce (millions)",
}
